---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: http
  package:
    name: httpie
    state: latest
- name: install HAProxy
  yum:
    name=haproxy 
    state=latest
- name: enable HAProxy
  service:
    name: haproxy
    state: started
- name: configure haproxy
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: restart HAproxy
  service:
    name: haproxy
    state: restarted